### ISSUE TITLE
Readthedocs 0-2-0 is broken

### ISSUE THREAD

**Issue by aawdls** [dls-controls/pytac#102]
The 0-2-0 build of the docs on readthedocs failed so the link to them isn't working.
https://readthedocs.org/projects/pytac/builds/8773511/
It might not be straightforward to fix for that existing tag, but the fact that it is building for "latest" means it has probably already been fixed for new releases.

**Comment by T-Nicholls** [comment]
Hi Andy,
Good catch, and you are correct that this has already been fixed.
I think it should be relatively straightforward to rebuild it for that tag, but since we will be making a new release of Pytac soon I'm not sure whether it's necessary.
