### ISSUE TITLE
Complications setting values on corrector magnets

### ISSUE THREAD

**Issue by willrogers** [dls-controls/pytac#88]
Until now, we have been setting values on corrector magnets using the fields `a0` and `b0`. This is appropriate for the corrector magnets embedded in sextupoles, for which AT uses `StrMPoleSymplectic4Pass`, which in turn uses `PolynomA` and `PolynomB` for its calculations.

However, there are standalone corrector magnets, and these are using the `KickAngle` property in AT. This is different to the `Polynom[AB][0]` by (I think) a factor of the length of the magnet.

In MML, I think the physics units refer to kick angle, and the AT values are set appropriately depending on the type of corrector. We have to handle the two different cases appropriately.

There is potentially a similar problem for the quadrupole magnets, which could use either `PolynomB[1]` or `K` depending on the pass method used.

@T-Nicholls does this describe the problem as you understand it?

**Comment by T-Nicholls** [comment]
@willrogers this is the MML code for setting HCMs, as you can see it involves Roll so I am not quite sure how that translates for pytac.

```if any(strcmpi(AT.ATType, {'HCM','Kicker'}))
% HCM
for i = 1:size(NewSP,1)
    % Coupling: Magnet roll is part of the AT model
    %           The gain is part of hw2physics/physics2hw
    if isfield(THERING{ATIndexList(i)}, 'Roll')
        Roll = THERING{ATIndexList(i)}.Roll;
    else
        % Knowing the cross-plane family name can be a problem
        % If the VCM family has the same AT index, then use it.
        Roll = [getroll(Family, Field, DeviceList(i,:))  0];
        VCMDevList = family2dev('VCM');
        iVCM = findrowindex(DeviceList(i,:), VCMDevList);
        if ~isempty(iVCM)
            try
                ATIndexVCM = family2atindex('VCM', DeviceList(i,:));
                if ATIndexVCM == ATIndexList(i)
                    Roll = [Roll(1) getroll('VCM', Field, DeviceList(i,:))];
                else
                    Roll = [0 0];
                end
            catch
            end
        end
    end
    if isfield(THERING{ATIndexList(i)}, 'KickAngle')
        % New X-Kick, but the Y-Kick needs to be maintained (middle layer coordinates)
        XKick = NewSP(i);
        YKick = [-sin(Roll(1)) cos(Roll(1))] * THERING{ATIndexList(i)}.KickAngle(:) / (cos(Roll(1)-Roll(2)));
        % Superimpose the X and Y kicks
        THERING{ATIndexList(i)}.KickAngle(1) = XKick * cos(Roll(1)) - YKick * sin(Roll(2));
        THERING{ATIndexList(i)}.KickAngle(2) = XKick * sin(Roll(1)) + YKick * cos(Roll(2));
        %fprintf('kick(%d,%d)=%g %g  AT=%g %g  Roll=%g  %g\n',DeviceList(i,:), XKick, YKick, THERING{ATIndexList(i)}.KickAngle, Roll);
        %% X only kick
        %THERING{ATIndexList(i)}.KickAngle(1) = NewSP(i) * cos(Roll(1));
        %THERING{ATIndexList(i)}.KickAngle(2) = NewSP(i) * sin(Roll(1));
    else
        XKick = NewSP(i);
        THERING{ATIndexList(i)}.PolynomB(1) = -XKick ./ THERING{ATIndexList(i)}.Length;
    end
end
```

**Comment by willrogers** [comment]
`Roll` takes into account any rotational misalignment of the magnets. If zero, it shouldn't have any effect on the calculations. As far as I can tell, all of the roll values in the ring are zero, so I don't think this is what's causing that effect.

`sin(0) = 0` and `cos(0) = 1`, so

```
YKick = [-sin(Roll(1)) cos(Roll(1))] * THERING{ATIndexList(i)}.KickAngle(:) / (cos(Roll(1)-Roll(2)));
```

simplifies to 

```
YKick = [0 1] * THERING{ATIndexList(i).KickAngle(:) / 1
```

i.e. the original `YKick`

**Comment by T-Nicholls** [comment]
So after much investigation, I can finally confirm that the formula stands, that is:
- PolynomB = - KickAngle/Length
- PolynomA = + KickAngle/Length
Being negative for horizontal corrector magnets and positive for the vertical ones. Roll is not a factor in our simulation.
Currently, our unitconv object for the corrector magnets does not divide by the length of the element and so is the correct unitconv for KickAngle, with PolynomA/B adjustments being made later.

**Comment by willrogers** [comment]
Note that the calculations we do for orbit correction are working correctly because:

* the output of the calculation returns us kick angle
* the unit conversion correctly converts this into amps

In Pytac we incorrectly call this `b0`, but that doesn't affect the outcome.

**Comment by T-Nicholls** [comment]
I believe the changes on pull request #90 along with those I have made to atip should have solved all these issues now.
